name: Regenerate CRDs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  regenerate-crds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Install dependencies
        run: |
          go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.14.0
          go install github.com/mikefarah/yq/v4@v4.25.3
          sudo apt-get install -y kustomize

      - name: Regenerate CRDs
        run: make manifests

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add config/crd/bases/*.yaml
          git commit -m 'Regenerate CRDs'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
